spring:
  data:
    mongodb:
      uri: mongodb://sdp-sn-admin:SDP20SNADM%402022@10.137.136.14:27017/orbis_street_name?authSource=admin
      database: orbis_street_name
  application:
    name: tags-application
server:
  port: 9000
  servlet:
    context-path: /tags-application

springdoc:
  swagger-ui:
    use-root-path: true